const details={
"01":{challenge:"Large financial institutions operate across complex products, data sets and control environments. AI can support research, risk detection, service and internal productivity, but deployment has to fit existing governance and controls.",solution:"Machine learning, natural-language systems and workflow automation are used across selected finance and banking processes, with human review retained for material decisions.",implementation:"The practical pattern is incremental: identify high-volume information tasks, connect governed data sources, test models, monitor outputs and place approval controls around higher-risk actions.",impact:"AI can reduce manual information handling and accelerate analysis, while changing how finance professionals spend time. The strongest implementations treat model governance and data quality as part of the finance process, not as an afterthought.",lessons:["Start with bounded workflows rather than uncontrolled automation.","Keep auditability and human review for material financial decisions.","Measure accuracy, exceptions and time saved—not only model output."],sources:[["JPMorgan Chase — AI research and technology","https://www.jpmorganchase.com/technology/artificial-intelligence"]],metric:"AI + ML",metricLabel:"Core technologies"},
"03":{challenge:"Small businesses need accounting support without adding complex manual workflows. The opportunity for generative AI is to turn financial information into explanations, recommendations and guided actions.",solution:"Intuit has integrated generative AI capabilities into its small-business financial ecosystem to assist with financial questions, insights and workflows.",implementation:"AI features sit alongside accounting data and existing software workflows, allowing users to ask questions or receive contextual assistance while retaining user control over financial actions.",impact:"The case illustrates how accounting software is shifting from record-keeping toward an interactive financial assistant model. Accuracy, privacy and clear user review remain essential because the underlying information is financial data.",lessons:["AI assistance works best when grounded in the user's financial context.","Generated recommendations should remain reviewable before posting or filing.","The interface matters: useful AI reduces complexity rather than adding another tool."],sources:[["Intuit — AI / investor resources","https://investors.intuit.com/"]],metric:"GenAI",metricLabel:"Technology focus"},
"31":{challenge:"Account reconciliation is repetitive but financially important. Finance teams need automation without losing transparency over how matches and exceptions were produced.",solution:"BlackLine's Verity platform uses governed AI and multi-agent capabilities to support reconciliation preparation while emphasizing auditability and human oversight.",implementation:"AI agents can work through preparation tasks and surface exceptions, while finance professionals remain responsible for review, controls and final decisions.",impact:"The model demonstrates a direction for accounting automation: move repetitive preparation to software while preserving evidence, review and governance around the financial close.",lessons:["Governed automation is more suitable for accounting than opaque automation.","Exceptions should be surfaced clearly for human review.","Audit trails need to remain part of the workflow."],sources:[["BlackLine — Verity","https://www.blackline.com/solutions/ai/"]],metric:"Multi-agent AI",metricLabel:"Reconciliation"},
"35":{challenge:"AI agents are increasingly capable of performing actions rather than only generating text. In payments, this creates a need to identify agents and manage transaction permissions and risk.",solution:"NPCI has been developing work around an AI-agent registry for UPI to support identification and monitoring of agents that transact through the payments ecosystem.",implementation:"The emerging model places an identity and governance layer around agentic payment activity, complementing existing payment rails and controls.",impact:"Agentic payments could make software an active participant in financial transactions. That increases the importance of authentication, consent, transaction limits, monitoring and accountability.",lessons:["An AI agent needs a clear identity and authority boundary.","Payment controls should apply to machine-initiated actions as well as human actions.","New automation should be evaluated for fraud, privacy and operational risks."],sources:[["Reuters — India plans AI registry for agentic UPI payments","https://www.reuters.com/"]],metric:"Agentic UPI",metricLabel:"Emerging framework"}
};

const fallbackCases={
"02":["02","Microsoft","AI & Finance Operations","AI and automation applied to finance operations, analysis and business workflows.","AI","ACCOUNTING"],
"04":["04","EY","Generative AI & Audit","Generative AI applications across audit, research and professional-services workflows.","AI","AUDIT"],
"05":["05","Deloitte","Intelligent Automation","RPA and intelligent automation applied across finance and accounting processes.","RPA","ACCOUNTING"],
"06":["06","PwC","Automation in Finance","Intelligent automation used to streamline repetitive finance workflows.","RPA","FINANCE"],
"07":["07","UiPath","Accounts Payable Automation","Automation of repetitive invoice-processing and accounts-payable workflows.","RPA","ACCOUNTING"],
"08":["08","Walmart","Blockchain Supply Chain","Blockchain used to improve traceability and information sharing across supply-chain processes.","BLOCKCHAIN","SUPPLY CHAIN"],
"09":["09","Maersk","Blockchain & Global Trade","Distributed-ledger technology applied to trade documentation and logistics.","BLOCKCHAIN","FINTECH"],
"10":["10","JPMorgan","Blockchain Financial Infrastructure","Blockchain-based infrastructure explored for institutional financial transactions.","BLOCKCHAIN","BANKING"],
"11":["11","Xero","Cloud Accounting","Cloud accounting enabling real-time access, collaboration and integrations.","CLOUD","ACCOUNTING"],
"12":["12","Intuit QuickBooks","Cloud Finance","Cloud-based accounting connecting bookkeeping, reporting and business workflows.","CLOUD","ACCOUNTING"],
"13":["13","SAP","Cloud ERP & Finance","Cloud financial-management systems integrating accounting with enterprise operations.","CLOUD","ERP"],
"14":["14","Oracle","Cloud Financial Management","Cloud-based financial management, reporting and enterprise accounting capabilities.","CLOUD","ERP"],
"15":["15","UPI","India's Digital Payments Ecosystem","Interoperable instant-payment infrastructure and its impact on digital transactions.","FINTECH","PAYMENTS"],
"16":["16","PhonePe","Digital Payments","Digital-payments platform built around India's expanding payments infrastructure.","FINTECH","PAYMENTS"],
"17":["17","Razorpay","Payment Infrastructure","Financial infrastructure connecting businesses with digital payment collection and transaction tools.","FINTECH","PAYMENTS"],
"18":["18","Stripe","Payments Infrastructure","APIs and financial infrastructure enabling online businesses to accept and manage payments.","FINTECH","PAYMENTS"],
"19":["19","Revolut","Digital Banking","Technology-led banking services combining payments, accounts and financial products.","BANKING","FINTECH"],
"20":["20","Nubank","Digital-First Banking","Digital-first banking model built around mobile technology and scalable financial services.","BANKING","FINTECH"],
"21":["21","Morgan Stanley","AI & Wealth Management","AI-assisted tools explored for research, productivity and wealth-management workflows.","AI","WEALTHTECH"],
"22":["22","DBS Bank","Digital Transformation","Technology-led transformation of banking operations and customer experiences.","BANKING","DIGITAL"],
"23":["23","ICICI Bank","Digital Banking","Digital channels and technology used to transform customer banking services.","BANKING","INDIA"],
"24":["24","Goldman Sachs","AI in Finance","AI applications across research, software development and financial workflows.","AI","BANKING"],
"25":["25","Deloitte","Blockchain & Audit","Distributed-ledger technology explored for audit and assurance applications.","BLOCKCHAIN","AUDIT"],
"26":["26","KPMG","Automation & Audit","Automation and analytics applied to audit and finance processes.","RPA","AUDIT"],
"27":["27","Siemens","Finance Process Automation","Automation used to improve finance-process efficiency at enterprise scale.","RPA","FINANCE"],
"28":["28","Microsoft Dynamics","Cloud Finance","Cloud financial-management tools connecting accounting, ERP and business analytics.","CLOUD","ERP"],
"29":["29","Razorpay","Embedded Finance","Financial capabilities embedded into digital business workflows and platforms.","FINTECH","PAYMENTS"],
"30":["30","Stripe","Embedded Financial Services","Financial infrastructure APIs extending payment capabilities into broader software ecosystems.","FINTECH","PAYMENTS"],
"32":["32","Pilot","AI Month-End Close","AI accounting platform designed to automate month-end close work and return review-ready financials.","AI","ACCOUNTING"],
"33":["33","Karbon Business","AI Accounting for SMEs","AI-powered accounting platform offering bookkeeping, reconciliation, GST and financial-visibility tools.","AI","ACCOUNTING"],
"34":["34","Ramp","AI Accounting Operations","AI-first financial-management software expanding into accounting and automating basic finance tasks.","AI","FINTECH"]
};

const allCases=window.caseStudies||Object.values(fallbackCases);
const id=new URLSearchParams(location.search).get("id")||"01";
const row=allCases.find(x=>x[0]===id)||fallbackCases[id]||allCases[0];
const d=details[id]||{challenge:`${row[1]} is a useful example of ${String(row[2]).toLowerCase()}. The case is presented as a technology-and-accounting study: what problem the technology addresses, how it changes the workflow and what controls matter.`,solution:row[3],implementation:`The implementation can be understood through the finance workflow: identify repetitive or information-heavy tasks, connect the required data and systems, automate where rules are reliable, and route exceptions to people.`,impact:`The financial impact depends on adoption, process design and control quality. Typical effects include faster processing, better visibility, fewer manual handoffs and more time for analysis, while introducing technology, governance and change-management requirements.`,lessons:["Map the existing process before automating it.","Define controls, ownership and exception handling.","Measure operational outcomes alongside technology performance."],sources:[["LEVEL UP research note — technology in accounting","https://www.icmai.in/"]],metric:row[4],metricLabel:"Technology category"};

const idx=allCases.findIndex(x=>x[0]===id);
const prev=allCases[(idx-1+allCases.length)%allCases.length];
const next=allCases[(idx+1)%allCases.length];
document.title=`${row[1]} — ${row[2]} | LEVEL UP`;
const article=document.getElementById("caseArticle");
if(article){
article.innerHTML=`<section class="case-hero"><div class="eyebrow">CASE ${row[0]} / ${row[4]} / ${row[5]}</div><h1>${row[1]}<br>${row[2]}</h1><p class="case-dek">${row[3]}</p><div class="meta"><span>${row[4]}</span><span>${row[5]}</span><span>LEVEL UP RESEARCH</span></div></section><section class="case-layout"><article><h2>The challenge</h2><p>${d.challenge}</p><h2>The technology</h2><p>${d.solution}</p><h2>Implementation</h2><p>${d.implementation}</p><h2>Accounting & financial impact</h2><p>${d.impact}</p><h2>Key lessons</h2><ul>${d.lessons.map(x=>`<li>${x}</li>`).join("")}</ul><div class="sources"><div class="eyebrow">SOURCES & FURTHER READING</div>${d.sources.map(s=>`<a href="${s[1]}" target="_blank" rel="noopener">${s[0]} ↗</a>`).join("")}</div></article><aside class="impact"><div class="eyebrow">PROOF SNAPSHOT</div><div class="stat">${d.metric}</div><small>${d.metricLabel}</small><div class="stat">${row[4]}</div><small>Primary technology theme</small><div class="stat">${row[5]}</div><small>Sector / context</small></aside></section><nav class="case-nav"><a href="case-study.html?id=${prev[0]}"><span>PREVIOUS</span>← ${prev[1]}</a><a href="case-study.html?id=${next[0]}"><span>NEXT</span>${next[1]} →</a></nav>`;
}
const tickerItems=["AI IN ACCOUNTING","FINTECH DEVELOPMENTS","DIGITAL PAYMENTS","RPA & AUTOMATION","BLOCKCHAIN","CLOUD ACCOUNTING","GENERATIVE AI","FINANCIAL TECHNOLOGY"];
const ticker=document.getElementById("tickerTrack"); if(ticker)ticker.innerHTML=[...tickerItems,...tickerItems].map(x=>`<span>${x}</span>`).join("");
const dialog=document.getElementById("searchDialog"); const openSearch=document.getElementById("openSearch"); const closeSearch=document.getElementById("closeSearch"); if(openSearch&&dialog)openSearch.onclick=()=>dialog.showModal(); if(closeSearch&&dialog)closeSearch.onclick=()=>dialog.close();
const gs=document.getElementById("globalSearch"); if(gs){gs.addEventListener("input",()=>{const q=gs.value.toLowerCase().trim();const box=document.getElementById("searchResults");box.innerHTML=allCases.filter(c=>c.slice(1).join(" ").toLowerCase().includes(q)).slice(0,8).map(c=>`<a class="result" href="case-study.html?id=${c[0]}"><strong>${c[1]}</strong><small>${c[2]} · ${c[4]}</small></a>`).join("")||(q?'<p style="color:#777">No results found.</p>':'');});}
